# Generated by Django 5.1.6 on 2025-04-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='photos/kr.jpg', upload_to='photos'),
        ),
    ]
